spring:
  datasource:
    url: ${SQLITE_DB_URL:jdbc:sqlite:webapp.db}
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    hikari:
      maximum-pool-size: 1
      connection-init-sql: "PRAGMA journal_mode=WAL; PRAGMA busy_timeout=30000; PRAGMA foreign_keys=ON"

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  flyway:
    enabled: false

  sql:
    init:
      mode: always
